/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pt.ua.estga.bibliotecavirtual;

import javax.swing.JOptionPane;

/**
 *
 * @author arti
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardUtilizador
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        dashboardLivro = new javax.swing.JButton();
        dashboardCategoria = new javax.swing.JButton();
        dashboardUtilizador = new javax.swing.JButton();
        dashboardStaff = new javax.swing.JButton();
        atualizarPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dashboard Admin");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        dashboardLivro.setText("Dashboard Livro");
        dashboardLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardLivroActionPerformed(evt);
            }
        });

        dashboardCategoria.setText("Dashboard Categoria");
        dashboardCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardCategoriaActionPerformed(evt);
            }
        });

        dashboardUtilizador.setText("Dashboard Utilizador");
        dashboardUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardUtilizadorActionPerformed(evt);
            }
        });

        dashboardStaff.setText("Dashboard Staff");
        dashboardStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardStaffActionPerformed(evt);
            }
        });

        atualizarPerfil.setText("Atualizar Perfil");
        atualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dashboardCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dashboardUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dashboardStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atualizarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sair))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardLivro)
                    .addComponent(dashboardUtilizador))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardCategoria)
                    .addComponent(dashboardStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(atualizarPerfil)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardLivroActionPerformed
        // Cria uma instância da interface DashboardLivro
        DashboardLivro registerWindow = new DashboardLivro();

        // Mete a janela DashboardLivro visível
        registerWindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_dashboardLivroActionPerformed

    private void dashboardCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCategoriaActionPerformed
        // Cria uma instância da interface DashboardCategoria
        DashboardCategoria registerWindow = new DashboardCategoria();

        // Mete a janela DashboardCategoria visível
        registerWindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_dashboardCategoriaActionPerformed

    private void dashboardUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardUtilizadorActionPerformed
        // Cria uma instância da interface TabelaUtilizador
        TabelaUtilizador registerWindow = new TabelaUtilizador();

        // Mete a janela TabelaUtilizador visível
        registerWindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_dashboardUtilizadorActionPerformed

    private void dashboardStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardStaffActionPerformed
        if (SessaoUtilizador.isFuncionario() && SessaoUtilizador.getIdCargo() == 1) {
            DashboardStaff dashboardStaff = new DashboardStaff();
            dashboardStaff.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Acesso negado. Apenas funcionários com cargo de administrador podem aceder a esta página.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_dashboardStaffActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // Cria uma instância da interface LoginInterface
        LoginInterface registerWindow = new LoginInterface();

        // Mete a janela LoginInterface visível
        registerWindow.setVisible(true);

        this.dispose();    }//GEN-LAST:event_sairActionPerformed

    private void atualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPerfilActionPerformed
        // Cria uma instância da interface AtualizarPerfilStaff
        AtualizarPerfilStaff registerWindow = new AtualizarPerfilStaff();

        // Mete a janela AtualizarPerfilStaff visível
        registerWindow.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_atualizarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarPerfil;
    private javax.swing.JButton dashboardCategoria;
    private javax.swing.JButton dashboardLivro;
    private javax.swing.JButton dashboardStaff;
    private javax.swing.JButton dashboardUtilizador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
